### ISSUE TITLE
mA for usb

### ISSUE THREAD

**Issue by odemolay** [jeanthom/TrinityEnabler#1]
hello thank you for your job!
i was wondering why did you choose 500 mA 1500mA 3000mA 4000mA settings ?

USB2 delivery is 500mA this one is good
USB3 delivery is 950mA so 1500mA should make problems dont you think ? 1000 would be appropriate

would you tell me more please?

**Comment by jeanthom** [comment]
Those mA ratings corresponds to EQ settings that are uploaded to the DAC chip. I'm unable to guess how to tweak the EQ settings yet, so I'm using Apple's settings. I guess they choose those values because they were matching the PowerMac G4 Cube USB ports power delivery capacity.
