### ISSUE TITLE
Trinity Enabler for Debian?

### ISSUE THREAD

**Issue by dickcolburn02** [jeanthom/TrinityEnabler#4]
Thank you for making these classic speakers functional on my newer Mac!  What I really want to do is use them on a Volumio jukebox on a Raspberry Pi.  That would require a port to Debian, I guess using libusb.  Do you have any insights or suggestions before I dig into understanding linux USB protocols?

Thanks!

**Comment by jeanthom** [comment]
Hi!

I started writing a reply... but I ended realizing that it would take me more time to describe how to do it than to do it myself... so there you go: https://github.com/jeanthom/TrinityEnablerLinux (untested, I don't own these speakers).

In brief, I replaced every bit of IOKit code with libusb code. Most of the "work" lies in rewriting xdfpSetMem, everything else is just replacing macOS-specific types with generic types (UInt32 -> uint32_t for instance). I also took the opportunity to do a little bit of cleaning. TrinityEnabler was -at the time- one of my biggest C projects.

**Comment by dickcolburn02** [comment]
Thank you!  Tomorrow I hope to get a Debian build working and try it out.  I really appreciate your quick response.

**Comment by dickcolburn02** [comment]
I had a tough time getting it to link.  I had to put main.o before libusb in the Makefile to get a good build.  It is failing when I run it on the Raspberry Pi:

volumio@volumio:~$ ./trinityenabler --power-4000
Audio device set to 4000mA
No suitable device found, exiting.
volumio@volumio:~$ lsusb -d 05ac:1101
Bus 001 Device 005: ID 05ac:1101 Apple, Inc. Speakers

Any ideas?

**Comment by dickcolburn02** [comment]
Part of what I pasted was interpreted as format commands.  Here it is again:

volumio@volumio: ./trinityenabler --power-4000
Audio device set to 4000mA
No suitable device found, exiting.
volumio@volumio: lsusb -d 05ac:1101
Bus 001 Device 005: ID 05ac:1101 Apple, Inc. Speakers

**Comment by jeanthom** [comment]
Did you try running it as root with sudo?

**Comment by dickcolburn02** [comment]
It got a little further:

volumio@volumio: sudo ./trinityenabler --power-4000
[sudo] password for volumio: 
Audio device set to 4000mA
Error while disabling plugin.

**Comment by jeanthom** [comment]
I need more debugging info, could you please update to the latest version of TrinityEnablerLinux? I added a little bit of logging in xdfpSetMem.

Thanks for your help.

**Comment by dickcolburn02** [comment]
I will do that.

I have been doing some debugging research.  I found that , on success, libusb_control_transfer returns the number of bytes transferred.  The logic of the if conditions assumed any nonzero return was an error.  I changed that and printed out the return values.  They are come back as "1", which makes sense sometimes but not others.

**Comment by dickcolburn02** [comment]
I see you fixed the problem I found.  Here is the output:

pi@raspberrypi: $ sudo ./src/trinityenabler --power-3000
Audio device set to 3000mA
sizeof(pluginBinary) = 212

I suspect it only claims to have transferred one byte each call.

**Comment by jeanthom** [comment]
> The logic of the if conditions assumed any nonzero return was an error. I changed that and printed out the return values. They are come back as "1", which makes sense sometimes but not others.

You're right. I just pushed a fix for that.

EDIT: xdfpSetMem (and many other functions in TrinityEnabler) return 0 if successful, and something else when an error occurs.

**Comment by dickcolburn02** [comment]
I got this once:

Audio device set to 4000mA
xdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIPExdfpSetMem: libusb_control_transfer error LIBUSB_ERROR_PIP

and this once:

Audio device set to 4000mA
No suitable device found, exiting.

The rest of the time I got this:

Audio device set to 4000mA

but it doesn't appear to have worked.

**Comment by jeanthom** [comment]
Did you try replugging the speakers on each trial?

I tried improving libusb init/exit code, can you give it a try?

**Comment by dickcolburn02** [comment]
I had not been replugging every test; it is in another room.  I did replug it for this test.  I got this with your new code:

$ sudo ./src/trinityenabler --power-4000
Audio device set to 4000mA
trinityenabler: ../../libusb/os/threads_posix.h:46: usbi_mutex_lock: Assertion `pthread_mutex_lock(mutex) == 0' failed.
Aborted

I will be away from my computer for a bit, I have to cook dinner.8-)  Check back later.\

Thanks!

**Comment by jeanthom** [comment]
I pushed some more fixes, but I'm doubtful that will help...

**Comment by dickcolburn02** [comment]
I tried your latest code.  Prior to running it I unplugged and replugged the speakers.  The system recognized them as analog speakers.  With VLC I could plug in headphones to amp box and get output, but, after unplugging the headphones, I got nothing from the speakers themselves. After I ran your latest code, neither the system nor VLC saw the speakers.

**Comment by dickcolburn02** [comment]
Good news.  I commented out the calls to libusb_set_auto_detach_kernel_driver, libusb_claim_interface and libusb_release_interface and it is working!

Thank you for your help!

**Comment by jeanthom** [comment]
Awesome! Thanks for trying all those patches on your speakers. Enjoy the music! :)
